# The following properties are required for ostasien (productive) deployment.
# For productive deployment, all properties must be configured or enabled.
# Only relevant properties should be listed here; otherwise, they should be deleted.
# Unless otherwise specified, empty properties are relevant and must be configured.
# Temporary disabled properties require further configuration or other dependencies.

##############################################################################
# Basic                                                                      #
##############################################################################
# Configure base url, e.g. http://domain:port, without '/'. Temporary disabled to use default.
#MCR.baseurl=
# Requires MCR.baseurl, therefore temporary disabled.
#MIR.CanonicalBaseURL=%MCR.baseurl%/
MCR.NameOfProject=CrossAsia
MIR.projectid.default=crossasia
MIR.testEnvironment=false
# Displays a test instance info in the layout.
MIR.TestInstance=true

##############################################################################
# Access Control                                                             #
##############################################################################
# Disable access keys.
MCR.ACL.AccessKey.Strategy.AllowedObjectTypes=

MIR.Access.Strategy.Classifications=mir_access,state

# Grant author all permissions while document is in state submitted.
MCR.Access.Strategy.CreatorPermissions=read,writedb,view-derivate,deletedb

# Allow user role to search after all objects.
MIR.OwnerStrategy.AllowedRolesForSearch=admin,editor

##############################################################################
# Email                                                                      #
##############################################################################
MCR.Mail.Server=
# General sender mail address, e.g. mail@domain
MCR.Mail.Sender=

# Mail for events including self registration, e.g. <name> mail@domain
MCR.mir-module.EditorMail=
# Sender email for events, e.g. <name> mail@domain
MCR.mir-module.MailSender=

##############################################################################
# DOI                                                                        #
##############################################################################
MCR.DOI.Prefix=10.82099
MCR.DOI.HostingInstitution=Fachinformationsdienst (FID) Asien (TEST)

# Configuration is required, therefore service temporary disabled.
#MCR.PI.Service.Datacite=org.mycore.pi.doi.MCRDOIService
MCR.PI.Service.Datacite.MetadataService=MODSDOI
MCR.PI.Service.Datacite.RegisterBaseURL=%MCR.baseurl%
MCR.PI.Service.Datacite.Username=
MCR.PI.Service.Datacite.Password=
MCR.PI.Service.Datacite.RegisterURLContext=receive/$ID
MCR.PI.Service.Datacite.RegistrationPredicate=org.mycore.pi.condition.MCRPIPublishedPredicate
MCR.PI.Service.Datacite.Transformer=datacite
MCR.PI.Service.Datacite.Generator=crossasiaDOI

MCR.PI.Generator.crossasiaDOI=org.mycore.pi.MCRGenericPIGenerator
MCR.PI.Generator.crossasiaDOI.GeneralPattern=%MCR.DOI.Prefix%/$ObjectDate-$Count
MCR.PI.Generator.crossasiaDOI.DateFormat=yyyyMMdd
MCR.PI.Generator.crossasiaDOI.CountPrecision=3
MCR.PI.Generator.crossasiaDOI.Type=doi

MCR.PI.MetadataService.MODSDOI=org.mycore.mods.identifier.MCRMODSDOIMetadataService
MCR.PI.MetadataService.MODSDOI.Prefix=%MCR.DOI.Prefix%

##############################################################################
# URN                                                                        #
##############################################################################
MCR.URN.Resolver.MasterURL=https://nbn-resolving.org/

MCR.PI.MetadataService.MODSURN.Prefix=urn:nbn:de:0308

MCR.PI.Generator.TypeYearCountURN.GeneralPattern=urn:nbn:de:0308-$ObjectDate-$Count-
MCR.PI.Generator.TypeYearCountURN.DateFormat=yyyyMMdd
MCR.PI.Generator.TypeYearCountURN.CountPrecision=3

##############################################################################
# OAI Data Provider                                                          #
##############################################################################
MCR.OAIDataProvider.OAI2.RepositoryName=CrossAsia - Repositorium Ostasien
MCR.OAIDataProvider.OAI2.RepositoryIdentifier=%MCR.baseurl%
MCR.OAIDataProvider.OAI2.AdminEmail=xasia@sbb.spk-berlin.de
MCR.OAIDataProvider.OAI2.DeletedRecord=transient
MCR.OAIDataProvider.OAI2.DescriptionURI.EPrints=webapp:oai/oai-eprints.xml
MCR.OAIDataProvider.OAI2.DescriptionURI.Rights=webapp:oai/oai-rights.xml
MCR.OAIDataProvider.OAI2.RecordSampleID=%MIR.projectid.default%_mods_00000249

MCR.OAIDataProvider.RepositoryPublisherName=
MCR.OAIDataProvider.RepositoryPublisherPlace=
MCR.OAIDataProvider.RepositoryPublisherAddress=

# Define metadata formats.
MCR.OAIDataProvider.MetadataFormat.xMetaDissPlus.Schema=http://files.dnb.de/standards/xmetadissplus/xmetadissplus.xsd
MCR.OAIDataProvider.MetadataFormat.xMetaDissPlus.Namespace=http://www.d-nb.de/standards/xmetadissplus/
MCR.OAIDataProvider.OAI2.MetadataFormats=oai_dc,mods,epicur,xMetaDissPlus

# Configure xMetaDissPlus set
MCR.OAIDataProvider.OAI2.MapSetToQuery.xmetadissplus=derCount:[1 TO *] AND NOT(mods.type:video OR mods.type:research_data OR mods.type:journal OR mods.type:series) AND mods.identifier:urn\\\:nbn\\\:de\\\:0308* AND state:published AND objectType:mods
MCR.OAIDataProvider.OAI2.Sets.xmetadissplus.URI=webapp:oai/set_xmetadissplus.xml

# Define URN set.
MCR.OAIDataProvider.OAI2.Sets.urn.Query=mods.identifier:urn\\\:nbn\\\:de\\\:0308*
MCR.OAIDataProvider.OAI2.Sets.urn.URI=webapp:oai/set_urn.xml

# Override set specifications.
MCR.OAIDataProvider.OAI2.Sets=doc-type,open_access,openaire,driver,ec_fundedresources,GENRE,ddc,urn,xmetadissplus

# Switch to DINI2022 conformity.
MCR.OAIDataProvider.OAI2.Sets.doc-type.URI=xslStyle:classification2sets:classification:metadata:2:children:diniPublType2022
MCR.OAIDataProvider.OAI2.Sets.doc-type.Classification=diniPublType2022
MIR.xMetaDissPlus.diniPublType.classificationId=diniPublType2022
MIR.dc.diniPublType.classificationId=diniPublType2022
MIR.dc.ignoredClassificationIds=diniPublType

# Set friendly OAI interfaces.
MCR.OAIDataProvider.OAI2.Friends.OpenAgrar=https://openagrar.bmel-forschung.de/servlets/OAIDataProvider
MCR.OAIDataProvider.OAI2.Friends.DuEPublico=https://duepublico.uni-duisburg-essen.de/servlets/OAIDataProvider
MCR.OAIDataProvider.OAI2.Friends.DBThueringen=https://www.db-thueringen.de/servlets/OAIDataProvider
MCR.OAIDataProvider.OAI2.Friends.RosDok=https://rosdok.uni-rostock.de/oai

##############################################################################
# ePuSta                                                                     #
##############################################################################
# ePuSta endpoint is required, therefore temporarily disabled.
#MIR.ePuSta=show
MIR.ePuSta.providerURL=

##############################################################################
# Editor                                                                     #
##############################################################################
MIR.EditorForms.CustomIncludes=%MIR.EditorForms.CustomIncludes%,xslStyle:editor/mir2xeditor:webapp:editor/editor-customization.xed,xslStyle:editor/mir2xeditor:webapp:editor/ostasien-editor-includes.xed
# Exclude genres from licence validation.
MIR.Editor.Validate.Genre.Licence=journal newspaper series lecture blog

##############################################################################
# Frontend                                                                   #
##############################################################################
MIR.CustomLayout.JS=ostasien.js
# Additional style sheets.
MCR.URIResolver.xslIncludes.MyCoReWebPage=%MCR.URIResolver.xslIncludes.MyCoReWebPage%,ostasien-templates.xsl

# Override export transformer.
MCR.Export.Transformers=bibtex:BibTeX,mods:MODS,marcxml:MARCXML,ris:RIS,isi:ISI,pica3:PICA,mods2csv:CSV,mods2dc:DC,datacite:DataCite

##############################################################################
# Batch Editor                                                               #
##############################################################################
MCR.BatchEditor.servstate.Path2Remove=service/servstates[@class="MCRMetaClassification"]/servstate[@classid="state"][@categid="{0}"]
MCR.BatchEditor.servstate.Path2Add=service/servstates[@class="MCRMetaClassification"]/servstate[@inherited="0"][@classid="state"][@categid="{0}"]

##############################################################################
# Citation                                                                   #
##############################################################################
MIR.citationStyles=dependent/asian-anthropology,apa,chicago-author-date,chicago-author-date-de,bibtex,elsevier-harvard,springer-basic-author-date,din-1505-2
MCR.Export.CSL.Styles=%MIR.citationStyles%

##############################################################################
# Solr                                                                       #
##############################################################################
MCR.Solr.NestedDocuments=true

##############################################################################
# Enrichment                                                                 #
##############################################################################
MIR.OADOI.Mail.Address=

##############################################################################
# Misc                                                                       #
##############################################################################
# Disable classification sorting.
MCR.URIResolver.Classification.Sort.mir_licenses=false
MCR.URIResolver.Classification.Sort.mir_filetype=false
MCR.URIResolver.Classification.Sort.noteTypes=false

MIR.Matomo=true
