name: Maven Snapshot Deploy (Comment)

on:
  issue_comment:
    types: [created]

jobs:
  deploy-on-comment:
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/deploy-snapshot')
    uses: gbv/reposis_workflows/.github/workflows/maven-snapshot-from-command.yml@v1
    with:
      java-version: '17'
      command: ${{ github.event.comment.body }}
      command-user: ${{ github.event.comment.user.login }}
    secrets:
      MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
